package constants

const (
	SERVER_PORT = ":5000"

	LINK_MONGODB_URI = "mongodb://localhost:27017"

	LINK_RELATIVEPATH_CONSTANT = "/"

	LINK_LOGIN_RELATIVEPATH = "/login"
	LINK_USER_RELATIVEPATH  = "/user"

	LINK_API_GROUP_RELATIVEPATH         = "/api"
	LINK_BLOG_GROUP_RELATIVEPATH        = "/blog"
	LINK_API_BLOG_GROUP_ID_RELATIVEPATH = "/:id"

	LINK_TEMPLATE_LOGINPAGE_RELATIVEPATH    = "/loginpage"
	LINK_TEMPLATE_REGISTERPAGE_RELATIVEPATH = "/registerpage"
)
